#
# Travis CI config file
#

language: php
php:
  - '7.4'
  - '7.3'

cache:
  # Cache lives for 10 min
  # Default of 3m might not be long enough for all the runs
  timeout: 600
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.npm"

services:
  - mysql

install:
  - php --version
  - mysql --version
  - composer install --dev --no-interaction --verbose
  - cp .travis/env.travis.php env.php

before_script:
  - php artisan database:create --reset
  - php artisan migrate:refresh --seed

script:
  - vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --diff --using-cache=no
  - vendor/bin/phpunit --debug --verbose

after_failure:
  - cat storage/logs/*.log
