<?php
exit();
?>

APP_NAME=Shop
APP_ENV=dev
APP_KEY=base64:qcoRdH+uUGg/ohZ7Xhm2n0+O/SMDyMMXFw5U6SuA0bM=
APP_DEBUG=true
APP_URL=http://shop.test

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=shop
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=database
SESSION_LIFETIME=120
